# Generated by Django 2.2.4 on 2021-08-19 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books_review', '0002_auto_20210819_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
